name: Update master

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-master:
    runs-on: ubuntu-latest
    name: Update master
    steps:
    - name: Clone
      uses: actions/checkout@v2

    - name: Branch
      run: |
        git remote add upstream https://github.com/ParadiseSS13/Paradise.git
        git fetch upstream
        git pull upstream/master
        git branch -f paradise-update
        git checkout paradise-update
        git reset --hard upstream/master

    - name: Commit and Push
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf
        git config --local user.email "action@github.com"
        git config --local user.name "Master Update"
        git add .
        git reset .github
        git commit -m 'Merge latest Paradise to master'
        git push -f -u origin paradise-update

    - name: Create Pull Request
      uses: repo-sync/pull-request@v2
      with:
        source_branch: "paradise-update"
        destination_branch: "master"
        pr_title: "Automatic Paradise Update"
        pr_body: "This pull request updates master to the latest version of Paradise. Please note any breaking or unimplemented changes before merging."
        pr_label: "Infrastructure"
        pr_allow_empty: false
        github_token: ${{ secrets.GITHUB_TOKEN }}
